apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-app
  labels:
    app: bad-app  #### Note that there is no environment label for this Deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad-app
  template:
    metadata:
      labels:
        app: bad-app   
    spec:
      containers:
      - name: nginx
        image: nginx